### ISSUE TITLE
NullPointerException: getRadioVersion() must not be null

### ISSUE THREAD

**Issue by chaoscalm** [SebaUbuntu/Athena#20]
```
FATAL EXCEPTION: main
Process: dev.sebaubuntu.athena.dev, PID: 22106
java.lang.NullPointerException: getRadioVersion() must not be null
	at dev.sebaubuntu.athena.sections.BuildSection$dataFlow$1.invoke(BuildSection.kt:219)
	at dev.sebaubuntu.athena.sections.BuildSection$dataFlow$1.invoke(BuildSection.kt:244)
	at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:113)
	at kotlinx.coroutines.flow.FlowKt__CollectKt.emitAll(Collect.kt:109)
	at kotlinx.coroutines.flow.FlowKt.emitAll(Unknown Source:1)
	at dev.sebaubuntu.athena.viewmodels.SectionViewModel$special$$inlined$flatMapLatest$1.invokeSuspend(Merge.kt:193)
	at dev.sebaubuntu.athena.viewmodels.SectionViewModel$special$$inlined$flatMapLatest$1.invoke(Unknown Source:13)
	at dev.sebaubuntu.athena.viewmodels.SectionViewModel$special$$inlined$flatMapLatest$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:34)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:8)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:33)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:37)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@308649d, Dispatchers.Main.immediate]
```
[crash.log](https://github.com/SebaUbuntu/Athena/files/14872943/crash.log)
[device.txt](https://github.com/SebaUbuntu/Athena/files/14872950/device.txt)

**Comment by chaoscalm** [comment]
Solved here: https://github.com/SebaUbuntu/Athena/commit/1e2d77e349bde2f4655e5cd2a9e5df2e13d8e5e6
